"""Experimental diagram compiler over the R1 fixed-order family.

Research subsystem; see docs/DIAGRAM_COMPILER_TASK1.md,
docs/DIAGRAM_COMPILER_TASK2.md, and docs/DIAGRAM_COMPILER_TASK3.md, docs/DIAGRAM_COMPILER_TASK4.md,
and docs/DIAGRAM_COMPILER_TASK5.md.
Not part of the Future B v1.x release surface and not used by C0/P1.
"""

from .canonical import (
    IrError,
    build_scalar_diagram,
    build_scalar_ir,
    build_twoband_diagram,
    build_twoband_ir,
    chord_slots,
    diagram_id,
    enumerate_pairings,
    open_chord_slots,
    validate_ir,
)
from .cheap_cost import GraphCost, graph_cost, lower_exact_cost
from .cheap_evaluator import (
    CheapDag,
    CheapEvalError,
    CheapEvaluator,
    ExactEvaluator,
    P1_CORRESPONDENCE,
    compile_cheap,
    compile_exact,
    lower_cheap,
    odd_clip,
)
from .cheap_policy import (
    CheapPolicy,
    CheapPolicyError,
    POLICY_PROPAGATOR_ONLY_V1,
    propagator_only_v1,
)
from .da_kernel import (
    DAError,
    DATransitionResult,
    DelayedAcceptanceKernel,
    DelayedAcceptanceKernelSpec,
    acceptance_probability,
    compile_delayed_acceptance,
    delayed_acceptance_identity,
    ell_R_design_b,
    ell_hat_state_weight,
    transition_matrix,
)
from .fortran_codegen import emit_driver, emit_fortran
from .fortran_compile import compile_fortran_source, compile_native_kernel
from .native_interpret import NativeResult, interpret_native_kernel, native_acceptance_probability
from .native_ir import BindingLayout, NativeIRError, NativeKernelIR, binding_layout_for
from .native_lower import lower_native_kernel, lower_native_score_kernel
from .native_validate import exact_candidate_ops_on_reject_path, validate_native_ir
from .proposal import ProposalError, ProposalSpec
from .target_policy import TargetPolicy, TargetPolicyError, positive_real_F_v1
from .evaluator import (
    Binding,
    BindingError,
    compile_evaluator,
    evaluate_dag,
    evaluate_diagramwise,
    factor_value,
    numeric_close,
    validate_binding,
)
from .graph import DagNode, DagStats, EvalDag, leaf_key, lower_diagramwise, lower_grouped
from .ir import (
    MODEL_SCALAR,
    MODEL_TWOBAND,
    OBJECT_SHARED_X_GROUP,
    RULE_VERSION,
    SCHEMA_VERSION,
    SERIES_FULL,
    Diagram,
    DiagramIR,
    Factor,
    Family,
    MomentumForm,
    Variables,
)
from .r1_import import ImportRejected, import_r1_binding, import_r1_spec

__all__ = [
    "Binding",
    "BindingError",
    "BindingLayout",
    "CheapDag",
    "CheapEvalError",
    "CheapEvaluator",
    "CheapPolicy",
    "CheapPolicyError",
    "DAError",
    "DATransitionResult",
    "DagNode",
    "DagStats",
    "DelayedAcceptanceKernel",
    "DelayedAcceptanceKernelSpec",
    "Diagram",
    "DiagramIR",
    "EvalDag",
    "ExactEvaluator",
    "Factor",
    "Family",
    "GraphCost",
    "ImportRejected",
    "IrError",
    "MODEL_SCALAR",
    "NativeIRError",
    "NativeKernelIR",
    "NativeResult",
    "MODEL_TWOBAND",
    "MomentumForm",
    "OBJECT_SHARED_X_GROUP",
    "P1_CORRESPONDENCE",
    "ProposalError",
    "ProposalSpec",
    "POLICY_PROPAGATOR_ONLY_V1",
    "RULE_VERSION",
    "SCHEMA_VERSION",
    "SERIES_FULL",
    "TargetPolicy",
    "TargetPolicyError",
    "Variables",
    "acceptance_probability",
    "binding_layout_for",
    "build_scalar_diagram",
    "build_scalar_ir",
    "build_twoband_diagram",
    "build_twoband_ir",
    "chord_slots",
    "compile_cheap",
    "compile_delayed_acceptance",
    "compile_evaluator",
    "compile_exact",
    "compile_fortran_source",
    "compile_native_kernel",
    "emit_driver",
    "emit_fortran",
    "delayed_acceptance_identity",
    "diagram_id",
    "ell_R_design_b",
    "ell_hat_state_weight",
    "enumerate_pairings",
    "evaluate_dag",
    "exact_candidate_ops_on_reject_path",
    "evaluate_diagramwise",
    "factor_value",
    "graph_cost",
    "import_r1_binding",
    "interpret_native_kernel",
    "import_r1_spec",
    "leaf_key",
    "lower_cheap",
    "lower_native_kernel",
    "lower_native_score_kernel",
    "lower_diagramwise",
    "lower_exact_cost",
    "lower_grouped",
    "native_acceptance_probability",
    "numeric_close",
    "odd_clip",
    "open_chord_slots",
    "positive_real_F_v1",
    "propagator_only_v1",
    "transition_matrix",
    "validate_binding",
    "validate_ir",
    "validate_native_ir",
]
