"""Experimental diagram compiler over the R1 fixed-order family.

Research subsystem; see docs/DIAGRAM_COMPILER_TASK1.md and
docs/DIAGRAM_COMPILER_TASK2.md. Not part of the Future B v1.x release
surface and not used by C0/P1.
"""

from .canonical import (
    IrError,
    build_scalar_diagram,
    build_scalar_ir,
    build_twoband_diagram,
    build_twoband_ir,
    chord_slots,
    diagram_id,
    enumerate_pairings,
    open_chord_slots,
    validate_ir,
)
from .cheap_cost import GraphCost, graph_cost, lower_exact_cost
from .cheap_evaluator import (
    CheapDag,
    CheapEvalError,
    CheapEvaluator,
    ExactEvaluator,
    P1_CORRESPONDENCE,
    compile_cheap,
    compile_exact,
    lower_cheap,
    odd_clip,
)
from .cheap_policy import (
    CheapPolicy,
    CheapPolicyError,
    POLICY_PROPAGATOR_ONLY_V1,
    propagator_only_v1,
)
from .evaluator import (
    Binding,
    BindingError,
    compile_evaluator,
    evaluate_dag,
    evaluate_diagramwise,
    factor_value,
    numeric_close,
    validate_binding,
)
from .graph import DagNode, DagStats, EvalDag, leaf_key, lower_diagramwise, lower_grouped
from .ir import (
    MODEL_SCALAR,
    MODEL_TWOBAND,
    OBJECT_SHARED_X_GROUP,
    RULE_VERSION,
    SCHEMA_VERSION,
    SERIES_FULL,
    Diagram,
    DiagramIR,
    Factor,
    Family,
    MomentumForm,
    Variables,
)
from .r1_import import ImportRejected, import_r1_binding, import_r1_spec

__all__ = [
    "Binding",
    "BindingError",
    "CheapDag",
    "CheapEvalError",
    "CheapEvaluator",
    "CheapPolicy",
    "CheapPolicyError",
    "DagNode",
    "DagStats",
    "Diagram",
    "DiagramIR",
    "EvalDag",
    "ExactEvaluator",
    "Factor",
    "Family",
    "GraphCost",
    "ImportRejected",
    "IrError",
    "MODEL_SCALAR",
    "MODEL_TWOBAND",
    "MomentumForm",
    "OBJECT_SHARED_X_GROUP",
    "P1_CORRESPONDENCE",
    "POLICY_PROPAGATOR_ONLY_V1",
    "RULE_VERSION",
    "SCHEMA_VERSION",
    "SERIES_FULL",
    "Variables",
    "build_scalar_diagram",
    "build_scalar_ir",
    "build_twoband_diagram",
    "build_twoband_ir",
    "chord_slots",
    "compile_cheap",
    "compile_evaluator",
    "compile_exact",
    "diagram_id",
    "enumerate_pairings",
    "evaluate_dag",
    "evaluate_diagramwise",
    "factor_value",
    "graph_cost",
    "import_r1_binding",
    "import_r1_spec",
    "leaf_key",
    "lower_cheap",
    "lower_diagramwise",
    "lower_exact_cost",
    "lower_grouped",
    "numeric_close",
    "odd_clip",
    "open_chord_slots",
    "propagator_only_v1",
    "validate_binding",
    "validate_ir",
]
